OP5dev/TF-via-PR

.github/dependabot.yml
.github/workflows/terraform.yml

Add sample workflow with inputs

Add sample workflow with inputs

---

.github/workflows/terraform.yml

Format terraform workflow

---

.github/workflows/terraform.yml

Populate issue number

---

.github/workflows/terraform.yml

Script labels

---

.github/workflows/terraform.yml

Complete labels script

---

environments/prod/.terraform.lock.hcl

Add prod state lock file

---

environments/echo/networks.tf
environments/echo/policies.tf
environments/echo/providers.tf
environments/echo/routes.tf
environments/echo/secrets.tf
environments/echo/services.tf
environments/echo/variables.tf

Add echo ecs

---

.github/workflows/terraform-caller.yml
.github/workflows/terraform-runner.yml
.github/workflows/terraform.yml

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, …)
Feature
**What is the current behavior?** (We can also link to an open issue here)
One has to clone the terraform.yml workflow file in order to use it in their own repository. 
**What is the new behavior?** (If this is a feature change)
One is able to reference a versioned, reusable workflow directly from this repository: enabling future updates.
**Does this PR introduce a breaking change?** (What changes might users need to make in their 
application due to this PR?)
Yes.

Terraform Reusable Workflow

---

.env.sample
.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md
environments/backend.tfvars

**What kind of change does this PR introduce? (Bug fix, feature, docs update, …)**
Documentation.

Prepare docs for v3

---

.devcontainer/devcontainer.json

**What kind of change does this PR introduce?** (Fix, feature, documentation, …)
**What is the current behaviour?** (Link if there is an open issue)
**What is the new behaviour?** (If this is a feature change)
**Does this PR introduce a breaking change?** (Consider incompatibilities)

ci: codespace devcontainer for terraform

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/pull_request_template.md

chore: issue and pr templates

---

.gitignore
CODEOWNERS
CONTRIBUTING.md
SECURITY.md

docs: boilerplate

---

LICENSE

docs: adopt apache license

---

.env.sample
.github/dependabot.yml
stacks/modules/s3_bucket/main.tf
stacks/modules/s3_bucket/variables.tf
stacks/sample_bucket/.terraform.lock.hcl
stacks/sample_bucket/README.md
stacks/sample_bucket/backend/dev.tfvars
stacks/sample_bucket/backend/stg.tfvars
stacks/sample_bucket/main.tf
stacks/sample_bucket/providers.tf
stacks/sample_bucket/terraform.tfvars
stacks/sample_bucket/variables.tf
stacks/sample_instance/.terraform.lock.hcl
stacks/sample_instance/README.md
stacks/sample_instance/env/dev.tfvars
stacks/sample_instance/env/stg.tfvars
stacks/sample_instance/main.tf
stacks/sample_instance/providers.tf
stacks/sample_instance/variables.tf

refactor: sample stack examples

---

.github/workflows/caller.yml
.github/workflows/tf.yml
README.md

docs: cicd usage examples

---

README.md
stacks/sample_bucket/backend/dev.tfvars
stacks/sample_bucket/backend/stg.tfvars
stacks/sample_instance/providers.tf

chore: rename placeholder values

---

.github/workflows/caller.yml
.github/workflows/tf.yml

ci: rename vars

---

.github/workflows/caller.yml
.github/workflows/tf.yml
README.md
SECURITY.md

docs: prepare v5 release

---

.github/workflows/caller.yml
.github/workflows/caller_aws.yml
.github/workflows/tf.yml
README.md
SECURITY.md

Prepare-v7-1

---

.github/workflows/caller_aws.yml
.github/workflows/tf.yml

To account for [security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions).

fix: double encoding

---

.github/workflows/tf.yml
README.md

Feature to check if `CONFIG_TF_REQUIRE_APPROVAL` is set to "true". 
Not applicable. 
Verify that the PR review state is approved, otherwise exit the workflow with a failure. 
No.

feat: check pr approval

---

SECURITY.md

increment security supported version

---

.github/workflows/tf.yml

Replace a 3rd party dependency.
Yes, because `-terraform` keyword is replaced by `-tf`.
Fixes #142

replace peter-evans/find-comment

---

.github/workflows/tf.yml

Replace a 3rd party dependency.
Fixes: #141

replace myrotvorets/set-commit-status-action

---

.github/workflows/tf.yml

release v8.0.0

---

.github/workflows/tf.yml
README.md
action.yml

docs: update action name

---

.github/examples/tf_via_pr_comments.yml
.github/examples/tf_via_pr_comments_or_input.yml
.github/examples/tf_via_pr_input.yml
.github/examples/tf_via_pr_input_matrix.yml

ci: bump v10.1.0 release SHAs

---

README.md

docs: fix link reference

---

README.md
action.yml

ci: tweak default booleans

---

action.yml

chore(deps): bump actions/upload-artifact from 4.3.2 to 4.3.3

---

.github/workflows/tf_tests.yml
action.yml
scripts/comment_tf_output.js

ci: echo comment_id in tf_tests

---

README.md

docs: update name reference

---

SECURITY.md

list gha dependencies in security

---

.github/dependabot.yaml
stacks/sample_bucket/.terraform.lock.hcl
stacks/sample_instance/.terraform.lock.hcl

ci: add dependabot terraform deps

---

.github/examples/tf_via_pr_input_matrix.yaml
.github/workflows/tf_tests.yaml
action.yml
scripts/comment_tf_output.js

ci add `comment_summary` output

---

README.md
action.yml
scripts/comment_tf_output.js

Append outline of TFplan changes to the PR comment, [like so](https://github.com/DevSecTop/TF-via-PR/pull/213#issuecomment-2119313515).
Does not exist.
New feature.
No.

feat: outline of plan output changes

---

.github/dependabot.yaml

Follows on from https://github.com/dependabot/dependabot-core/issues/2178.

test: dependabot wildcard matching

---

README.md

Should be:
https://github.com/marketplace/actions/opentofu-terraform-via-pull-request

docs: fix marketplace link

---

scripts/comment_tf_output.js

Depending on "createe', "update" or "delete" change types, prefix the change outline lines with the appropriate diff indicator symbols.

feat: add diff indicators to change outline

---

.github/workflows/tf_tests.yaml
action.yml
action.yml.old
scripts/tf.js

- update tf_tests.yaml for new input parameters, broken out by each argument.
- use tenv for installation of terraform/tofu binary within the github action.

feat: prepare 11.0.0-rc.1

---

sample/bucket/.terraform.lock.hcl
sample/bucket/main.tf
sample/bucket/providers.tf
sample/bucket/terraform.tfvars
sample/bucket/variables.tf
sample/modules/s3_bucket/main.tf
sample/modules/s3_bucket/variables.tf

In order to test and verify Tofu's early-evaluation of variables in a public pipeline, https://github.com/opentofu/opentofu/issues/1042.

feat: replace with terraform s3-bucket module of variable version

---

.github/dependabot.yaml

Looking forward (optimistically) to https://github.com/opentofu/opentofu/issues/1236.

chore: dependabot tofu

---

.github/workflows/tf_destroy.yaml
sample/instance/README.md
sample/instance/main.tf

test: arg destroy with auto-approve

---

action.js
action.yml

Thanks to @chris3ware from https://github.com/3ware/aws-network-speciality/pull/50.

fix: auto-approve input

---

README.md

Improve wording and add more line breaks to ease legibility.

docs: tighten up wording and line breaks

---

.github/examples/pr_merge_matrix.yaml
.github/examples/pr_push_auth.yaml
.github/examples/pr_push_lint.yaml
.github/examples/pr_push_stages.yaml
.github/examples/pr_self_hosted.yaml
.github/examples/schedule_refresh.yaml
.github/workflows/tf_sample.yaml
README.md
SECURITY.md

GH organisation renamed from DevSecTop to [OP5dev](https://github.com/OP5dev).

docs: update name refs

---

README.md

While neither the project nor the organisation make any commitments in exchange for sponsorship, stating the names of sponsors at the end of the Readme could be included as a form of gratitude.

docs: add sponsors field

---

.github/workflows/tf_tests.yaml
README.md

ci: test with both `tofu` and `terraform` in multi-matrix

---

README.md

chore: update year

---

action.yml

fix: github server url ref

---

README.md
action.yml

Resolved #414.
- New `retention-days` input to configure the duration after which plan file artifact will expire (thank you, @ruzickap).

feat: upload artifact retention period

---

action.yml

| Before | After |
| --- | --- |
| `{owner}/{repo}` | `${{ github.repository }}` |
| `GITHUB_REF_NAME` | `${{ github.ref_name }}` |
| `GITHUB_RUN_ATTEMPT` | `${{ github.run_attempt }}` |
| `GITHUB_RUN_ID` | `${{ github.run_id }}` |
| `GITHUB_SHA` | `${{ github.event.pull_request.head.sha \|\| github.sha }}` |
| `GITHUB_TRIGGERING_ACTOR` | `${{ github.triggering_actor }}` |

chore: github variable substitution

---

README.md

docs: clarify plan-parity

---

.github/examples/pr_merge_matrix.yaml

Thanks to @bdalpe's input per [this comment](https://github.com/OP5dev/TF-via-PR/pull/426#issuecomment-2695205567).

docs: specify `arg-refresh` input for reliable plan-parity

---

.github/workflows/test_suite.yaml
action.yml

Resolves #440.
- Support for nested matrix structure in addition to existing flattened matrix input (thank you, @cornerman).

fix: nested matrix structure

---

action.yml

Resolves #459, thanks to @eumpek.

feat: expand workflow triggers

---

action.yml

fix: set default pr number to 0 if not found

---

.github/workflows/test_ci.yaml
action.yml

- Deletion of `apply` PR comment when `comment-pr: on-diff` (thank you, @birjj).
Resolves #506

fix: deletion of apply comment on-diff
