- .github/workflows/terraform.yml
**What kind of change does this PR introduce? (Bug fix, feature, docs update, …)**
Support for adding labels to bot-generated PRs, such as "dependabot[bot]" dependency updates.
**What is the current behavior? (We can also link to an open issue here)**
Due to the nature of dependabot's PR, the default labelling process overrides and negates the benefit of auto-applying Terraform environment labels steps of the workflow. 
**What is the new behavior? (If this is a feature change)**
By checking `contains(github.actor, '[bot]')` in addition to `github.event.action == 'opened'`, we should account for PRs like ones generated by dependabot. 
**Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)**
No.
> Add bot support

- .github/workflows/terraform.yml
**What kind of change does this PR introduce? (Bug fix, feature, docs update, …)**
Fixes labelling behaviour when a PR is opened with non-environment-related files modifications. 
**What is the current behavior? (We can also link to an open issue here)**
The add-labels step is run when it isn't required.
**What is the new behavior? (If this is a feature change)**
The add-labels step should only run if there are any relevant labels to add.
**Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)**
No.
> Add labels only on relevant file changes

- .github/workflows/tf.yml
- Fix terraform output on newline in collapsible content body
- Fix order priority in which collapsible content title is determined
- Fix var-file interpolation in the context of terraform plan, apply and auto-approve
- Fix terraform apply -auto-approve output to filter out lines related to reading or refreshing state
main
- Fix addition of PR label if it's there already
> ci: terraform output and interpolation fixups

- .github/workflows/tf.yml
fix: select the latest terraform output summary for collapsible content header
> fix: select the latest terraform output summary for collapsible content header

- action.yml
- stacks/sample_instance/main.tf
**Use-case scenario**
Provision resources in a workspaces with input variables, followed by targeted destruction.
For demo purposes, I have split out `plan` and `apply` outputs to separate comments, instead of updating the same one.
```bash
#1 PR Comment: Plan configuration in a workspace with input variable file.
-tf=plan -chdir=sample_instance -workspace=dev -var-file=env/dev.tfvars
#2 PR Comment: Apply configuration in a workspace with input variable file.
-tf=apply -chdir=sample_instance -workspace=dev -var-file=env/dev.tfvars
#3 PR Comment: Plan destruction of targeted resources in a workspace with input variable file.
-tf=plan -destroy -target=aws_instance.sample,data.aws_ami.ubuntu -chdir=sample_instance -workspace=dev -var-file=env/dev.tfvars
#4 PR Comment: Apply destruction of …
```
> ci: dynamic pr comment reaction

- action.yml
- scripts/add_commit_status.js
- scripts/add_pr_label.js
- scripts/add_reaction.js
- scripts/check_pr_approval.js
- scripts/comment_tf_output.js
- scripts/find_comment.js
- scripts/get_tf_plan_file.js
- scripts/update_commit_status.js
The `action.yml` is a massive file, full of nested JavaScript.
What if we could separate out the github-script steps into separate JavaScript files.
Just strip out the github-script steps into separate JavaScript files, [per discussion](https://github.com/actions/github-script/discussions/433).
From internal testing, I don't expect any breaking change.
> Separate out github-scripts to external files

- .github/examples/tf_via_pr_comments.yml
- .github/examples/tf_via_pr_comments_or_input.yml
- .github/examples/tf_via_pr_input.yml
- .github/examples/tf_via_pr_input_matrix.yml
- scripts/comment_tf_output.js
> docs: simplify pinned tags for legibility

- README.md
- action.yml
> docs: update naming

- action.yml
- scripts/comment_tf_output.js
> fix: plan output on error

- .github/workflows/tf_sample.yaml
In order to ensure AWS resources provisioned by TF have a chance to initialize before being deprovisioned again.
> fix: await resource initialization

- action.yml
- scripts/comment_tf_output.js
Logged #243 in order to document an example workflow to demonstrate the use-case scenario of `merge_group` event triggered workflow.
Resolves #242.
> feat: add support for `merge_group` trigger

- .github/examples/pr_merge_matrix.yaml
- .github/examples/pr_push_auth.yaml
- .github/workflows/tf_tests.yaml
- README.md
- Include `arg_lock` in all example workflows.
- Replace `tf_version` with dedicated TF setup step to simplify "getting started".
> docs: arg_lock and setup

- .github/workflows/tf_sample.yaml
To prevent erroneous runs of TF Sample workflow on merge to `main` branch.
> ci: fix event trigger

- action.js
Technically, this is a backwards-incompatible change, but any existing PRs would be updated before merging, which'd close any gaps anyway (<- terribly worded, I know).
Big thanks to @p4perf4ce for contributing from #272.
> feat: replace `-` separator with `.` in identifier

- .github/workflows/tf_sample.yaml
- .github/workflows/tf_tests.yaml
- README.md
- action.js
- action.yml
Provide an option to encrypt TF plan file before uploading as a repository artifact to prevent exposure of stored secrets.
- The [latest ubuntu runners](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#tools) (as of today) ship with OpenSSL 3.0.2-0ubuntu1.17.
- OpenSSL allows [de-/encryption](https://docs.openssl.org/3.0/man1/openssl-enc/) via [passphrase](https://docs.openssl.org/3.0/man1/openssl-passphrase-options/).
- Enable users to simply pass in `encrypt_passphrase: ${{ secrets.encryption_key }}`.
- Opted for "aes-256-ctr" (stream cipher mode) for bettter performance via parallelization, along with salt and pbkdf2.
- Must ~double~ triple-check that secrets passed in via `encrypt_passphrase` input is property masked in GitHub Action workflow logs. …
> feat: encrypt plan file with openssl

- README.md
- action.yml
Necessitated due to reports of breaking changes brought about by tenv [v3.2.0](https://github.com/tofuutils/tenv/releases/tag/v3.2.0) (PR https://github.com/tofuutils/tenv/pull/247).
> feat: pin `tenv` version

- .github/workflows/tf_tests.yaml
- README.md
- action.js
- action.yml
By default, the new `exitcode` [output parameter](https://github.com/DevSecTop/TF-via-PR?tab=readme-ov-file#outputs) will output `0` (succeeded) or `1` (failed).
By passing in `arg_detailed_exitcode: true`, then `exitcode` will return one of the [documented](https://opentofu.org/docs/cli/commands/plan/#other-options) exit codes:
- `0` = Succeeded with empty diff (no changes)
- `1` = Error
- `2` = Succeeded with non-empty diff (changes present)
Resolves #297.
> feat: expose tf exitcode

- .github/workflows/tf_sample.yaml
- action.js
- sample/instance/providers.tf
Since OpenTofu supports -var-file and -var input to [`init` command](https://opentofu.org/docs/cli/commands/init/#general-options) as part of their early (static) evaluation of variables/inputs.
> feat: pass variables to `init`

- .github/workflows/ci_release.yaml
- .github/workflows/tf_sample.yaml
- .github/workflows/tf_tests.yaml
> ci: update major release tag

- .github/examples/schedule_refresh.yaml
- README.md
- action.yaml
- Optionally run `init` only with `fmt` and/or `validate`, without subsequent `plan` or `apply` to aid lint/scan-specific workflows.
- Outputs:
- plan-id: ID of the plan file artifact.
- plan-url: URL of the plan file artifact.
- result: Result of the last TF command (truncated).
- summary: Summary of the last TF command.
- job-id: ID of the workflow job.
- run-url: URL of the workflow run.
- Multiline string outputs, and associated quoting.
- Order of command execution to: `fmt`* > `init` > `workspace`* > `validate`* > `plan`/`apply` (* optional).
- Cron-schedule workflow which checks for configuration drift now includes example to open an issue via GitHub CLI.
> feat: add outputs and improve workflow example

- README.md
Rarely serves its purposed nowadays due to in-built TF checks, though retained for exception use case within [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) workflow.
> docs: clarify plan-parity limited use

- action.yml
- fix: Include `stderr` the console output of the workflow run log.
- improve: Use `-json` for diff comparison of plan files with `plan-parity` enabled.
- fix: Exclude `-detailed-exitcode` from plan command during `plan-parity` comparison.
- improve: Reveal diff output if present when `plan-parity` comparison fails.
- improve: Append '…' ellipsis to truncated plan or diff outputs if exceeding character limit.
- add: Include count of diff lines in the output.
Resolved #337.
> patch: around `plan-parity` and truncation

- .github/workflows/tf_tests.yaml
- README.md
- action.yml
> [!NOTE]
> While this _is_ a patch release, existing PRs should be updated for consistent behaviour with plan files.
- Pass in multiple comma-separated `-backend-config` values (thank you, @fulgas).
E.g., `arg-backend-config: encrypt=true,bucket="bucket-name",dynamodb_table="table-name"`.
- This is in addition to existing support for `-var`, `-target`, and `-replace` comma-separated values.
- Portion of plan file artifact name is hashed with MD5 for concise, fixed-length string.
- This is to address GitHub's 256 character limit for artifact naming.
- As a bonus, this also masks potentially sensitive values from `arg-var` input.
- Documentation to include "To-Do" tasks.
- Handling of inputs which contain space(s) (e.g., `working-directory: "path to/directory"`).
- Handling of …
> feat: multiple backend-config inputs

- .github/workflows/tf_tests.yaml
- action.yml
- Reference workflow job ID from multiple chained matrices.
Resolves #355.
> fix: support multiple matrices

- action.yml
> fix: `push` event without associated pull request

- .github/examples/pr_push_stages.yaml
- .github/workflows/tf_tests.yaml
- README.md
- action.yml
- tests/pass_one/main.tf
Resolves #364.
https://github.com/DevSecTop/TF-via-PR/compare/v12.1.0...v13.0.0
The `comment-pr` input was overloaded as it determined the method of PR comment (i.e., `update` or `recreate`) in addition to whether a comment should be added at all (i.e., `none`). This has been simplified such that:
|Before|After|
|---|---|
|`comment-pr: update`|`comment-method: update` (default)|
|`comment-pr: recreate`|`comment-method: recreate`|
|`comment-pr: none`|`comment-pr: never` (or `on-change`)|
Following an organisation rename from [DevSecTop to OP5dev](https://github.com/orgs/OP5dev/discussions/7), references to the old name may result in "Unable to resolve action" until updated to `uses: op5dev/tf-via-pr@v13`.
- #370 New `tag-actor` parameter to tag the workflow triggering actor: `always` …
> feat: add `tag-actor` and `comment-method` input parameters

- .github/workflows/tf_tests.yaml
- action.yml
Resolves #354 (specifically @tenpaiyomi's [comment](https://github.com/OP5dev/TF-via-PR/issues/354#issuecomment-2563928831)).
- Determine PR number from `issue_comment` event trigger, in addition existing support for `push`, `pull_request` and `merge_group` events (thank you, @tenpaiyomi).
> fix: get pr for `issue_comment` event trigger

- .github/examples/pr_self_hosted.yaml
- .github/workflows/tf_tests.yaml
- README.md
Tangentially follows on from #354 regarding manual workflow trigger.
> docs: add `labeled` workflow example

- action.yml
Resolves #354 (specifically @tenpaiyomi's [comment](https://github.com/OP5dev/TF-via-PR/issues/354#issuecomment-2564154908)).
- The uniquely identifiable name now takes both `arg-target` and `arg-replace` inputs into account as well. This is in addition to existing support for the following input parameters:
- `arg-chdir` (i.e., `working-directory`)
- `arg-backend-config`
- `arg-var-file`
- `arg-var`
- `arg-workspace`
- `arg-destroy`
- `tool` (i.e., `tofu` or `terraform`)
- PR number.
> feat: add target and replaces args to identifier

- action.yml
- #380 Display timestamp for `issue_comment` event trigger (thank you, @tenpaiyomi).
> fix: display timestamp for `issue_comment` event trigger

- README.md
Following on from #382, we should list sponsors at the end of the Readme as gratitude for their support.
Tagging @chris3ware to confirm:
1. Permission to add @3ware to the sponsors list.
1. Preference on @3ware vs. @chris3ware handle.
Thank you.
> docs: add @3ware sponsor

- README.md
Following on from #382, we should list sponsors at the end of the Readme as gratitude for their support.
Tagging @tenpaiyomi to confirm:
1. Permission to add @StoatLabs to the sponsors list.
1. Preference on @StoatLabs vs. @tenpaiyomi handle.
Thank you.
> docs: add @StoatLabs sponsor

- README.md
Following on from #382, we should list sponsors at the end of the Readme as gratitude for their support.
Tagging @ego93 to confirm they're happy to be added to the sponsors list.
Thank you.
> docs: add @ego93 sponsor

- .github/examples/pr_self_hosted.yaml
- README.md
- action.yml
- Fallback on [actions/upload-artifact@v3](https://github.com/actions/upload-artifact) for GHE compatibility.
Resolves #399.
> feat: support github enterprise (ghe)

- .github/examples/pr_manual_label.yaml
- .github/examples/pr_self_hosted.yaml
- README.md
- action.yml
Resolves #402
- Support `workflow_dispatch` trigger from PR context (thank you, [OP5dev/Current-PR](https://github.com/OP5dev/Current-PR)).
- Workflow example with PR `labeled` and `workflow_dispatch` manual event triggers (thank you, @ruzickap).
> feat: expand manual trigger example

- action.yml
Resolved https://github.com/ctian1/TF-via-PR/pull/1/
- Delete any prior PR comment if `comment-pr: on-change` when there is no change (thank you, @ctian1).
> fix: delete pr comment on no change

- README.md
- action.yml
- Support comma-separated, multiple `arg-var-file` arguments (thank you, @sikhlana), in addition to existing support for:
- `arg-var`
- `arg-backend-config`
- `arg-replace`
- `arg-target`
> fix: multiple var-file

- .github/workflows/tf_tests.yaml
- action.yml
Resolves #416.
- Determination of PR number from branch (thank you, @nengelen-parloa).
> fix: get pr number from branch

- action.yml
Revert variable substitution from [environment variables](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables) to [contextual information](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs) within `jq` commands.
Fixes #424.
> fix: variable substitution in jq

- action.yml
Hey @bdalpe, thanks for sharing your fork! 
This looks like an excellent suggestion for `plan-parity` feature: how've you been find this in your workflow? 
Do you happen to leverage `merge_group` event trigger as well?
> improvement: Only compare resource changes

- .github/examples/pr_merge_matrix.yaml
- action.yml
Following on from #432, TF-via-PR currently makes a best-effort at checking if a PR label exists before creating it with a description and colour (5C4EE5).
However, on the very first run, this results in a suppressed error as it can't retrieve a PR label which doesn't exist yet, which can be confusing to new-users.
To "fix", TF-via-PR could simply not add a description or color, and just attach the "default" PR label with appropriate name (e.g., "tf:plan" or "tf:apply".
- #434 PR labels are no longer coloured #5C4EE5 to streamline label generation and attachment.
> change: add basic pr label

- .github/workflows/test_ci.yaml
- .github/workflows/test_suite.yaml
- README.md
- action.yml
Resolves #437
- #442 New `preserve-plan` input to preserve the plan file in the given working directory after workflow execution (default: `false).
- #442 New `upload-plan` input to upload plan file as GitHub workflow artifact (default: `true`).
> feat: optional plan file upload

- .github/workflows/test_ci.yaml
- README.md
- action.yml
This option will allow teams who prefer it, to draw more attention to the short resource diff and/or the detailed log views in the PR comment, to highlight potentially destructive changes more readily.
The default behavior of these new optional inputs matches the prior behavior, so there is no change for teams who do not opt in.
> feat: optional auto-open disclosure triangle for PR comment detail views

- action.yml
When you execute a matrix job, and the matrix is dynamic (i.e. based on the output of a previous job; for example, a change detection job that looks for workspaces that had changes), then GitHub won't immediately show the full job list for the current workflow run. You can observe this in the GitHub UI, where the matrix slowly gets more job instances, even as the matrix jobs instances are starting.
Unfortunately, even after a matrix job instance has started executing, it may not be visible in the UI or API yet. This means that the API call which TF-via-PR makes to get the job id is not guaranteed to succeed, and in practice it will reliably fail if the dynamic matrix is large enough (e.g. 50 instances), and if the `identifier` step of the `TF-via-PR` action is reached quickly enough.
This …
> fix: job id race condition with large, dynamic matrices

- action.yml
Resolves #452.
- Per recent [unannounced change](https://github.com/googleapis/release-please-action/issues/1105), GitHub API now requires `issues: write` permission in order to [create PR labels](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#create-a-label). As a GitHub Action, we don't want to extend our access/footprint any more than needed, so this patch suppresses any error from the "Label PR" step until GitHub makes a concrete announcement.
> patch: label pr continue on error

- action.yml
This fix allows the action to be run on the new data residency instances (https://github.com/newsroom/press-releases/data-residency-in-the-eu) which github offers for selected customers. New instances come with the following slug `COMPANY.ghe.com`, because of that, I've made an condition which further checks if the token provided has `ghe.com` in it's parameters.
Note, I've only tested these changes on the new `ghe.com` instance, not on a `github.com` one.
v4 upload
```bash
${{ inputs.command == 'plan' && inputs.upload-plan == 'true' && (github.server_url == 'https://github.com' || contains(github.server_url, '.ghe.com')) }}
```
v3 upload
```bash
${{ inputs.command == 'plan' && inputs.upload-plan == 'true' && !(github.server_url == 'https://github.com' || contains(github.server_url, …
```
> feat: support github enterprise data residency for australia and european union (sweden, netherlands)

- action.yml
Fixes #463.
- #464 The "view log" used to occasionally link to the step before TF-via-PR due to a race-condition.
> fix: redirect log link accurately

- action.yml
Prior to this commit, obtaining the job ID via gh CLI would fail when in a workflow with a job count that exceeds 100. For example, in a workflow with 105 jobs, the last 5 jobs fail to obtain their ids, because the 100-sized page didn't include them.
This PR fixes the issue by using the `--paginate` flag to list _all_ of the jobs even when they exceed 100 jobs. It uses the built-in pagination feature of the CLI that allows for using multiple pages under the hood when necessary, while still surfacing the output JSON as a single list (not split by pages).
This allows for workflows with arbitrarily-many jobs, at least up to the theoretical limits of how many JSON bytes we can pass around as a string inside our bash commands here.
> fix: workflow job list pagination to handle large job counts

- action.yml
Currently, differences found during the parity check will be output to stdout and thus the logs. This can leak secrets, as can be seen [here](https://github.com/perchnet/p/actions/runs/16870494518/job/47784366635#step:11:520)
This silences the diff output by doing the check with `diff -q`.
> Use `diff -q` during plan parity to prevent leaking secrets

- .github/examples/pr_manual_label.yaml
- .github/examples/pr_merge_matrix.yaml
- .github/examples/pr_push_auth.yaml
- .github/examples/pr_push_lint.yaml
- .github/examples/pr_push_stages.yaml
- .github/examples/schedule_refresh.yaml
- .github/workflows/test_aws.yaml
- .github/workflows/test_ci.yaml
- README.md
- action.yml
- Refactored user-controlled inputs to remediate potential code injection.
> fix: code injection security alerts
